#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
height=$(jq '.height' data.json)
weight=$(jq '.weight' data.json)
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

formatted_height=$(echo "$height" | awk '{printf "%.1f", $1 / 10}')
formatted_weight=$(echo "$weight" | awk '{printf "%.0f", $1 / 10}')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."

